const foodDatabase = {
  // ── SOUTH INDIAN ──────────────────────────────────────────────
  idli:              { calorie: 60,  protein: 2,  carbs: 12, fat: 0,  fiber: 0, category: "South Indian", emoji: "🫓" },
  dosa:              { calorie: 180, protein: 3,  carbs: 30, fat: 6,  fiber: 1, category: "South Indian", emoji: "🥞" },
  "masala dosa":     { calorie: 250, protein: 4,  carbs: 38, fat: 9,  fiber: 2, category: "South Indian", emoji: "🥞" },
  upma:              { calorie: 150, protein: 3,  carbs: 26, fat: 4,  fiber: 2, category: "South Indian", emoji: "🍚" },
  vada:              { calorie: 97,  protein: 1,  carbs: 14, fat: 4,  fiber: 1, category: "South Indian", emoji: "🍩" },
  sambar:            { calorie: 120, protein: 5,  carbs: 18, fat: 3,  fiber: 4, category: "South Indian", emoji: "🍲" },
  rasam:             { calorie: 80,  protein: 2,  carbs: 14, fat: 2,  fiber: 1, category: "South Indian", emoji: "🍵" },
  uttapam:           { calorie: 220, protein: 5,  carbs: 34, fat: 7,  fiber: 2, category: "South Indian", emoji: "🥞" },
  pongal:            { calorie: 200, protein: 4,  carbs: 30, fat: 7,  fiber: 2, category: "South Indian", emoji: "🍚" },
  "lemon rice":      { calorie: 230, protein: 3,  carbs: 42, fat: 6,  fiber: 1, category: "South Indian", emoji: "🍋" },
  "curd rice":       { calorie: 190, protein: 5,  carbs: 32, fat: 4,  fiber: 0, category: "South Indian", emoji: "🍚" },
  avial:             { calorie: 180, protein: 3,  carbs: 22, fat: 8,  fiber: 5, category: "South Indian", emoji: "🥘" },
  kozhambu:          { calorie: 150, protein: 2,  carbs: 20, fat: 7,  fiber: 3, category: "South Indian", emoji: "🍲" },
  idiyappam:         { calorie: 180, protein: 4,  carbs: 34, fat: 2,  fiber: 1, category: "South Indian", emoji: "🍝" },
  "medu vada":       { calorie: 110, protein: 2,  carbs: 16, fat: 5,  fiber: 1, category: "South Indian", emoji: "🍩" },
  "coconut chutney": { calorie: 90,  protein: 1,  carbs: 8,  fat: 6,  fiber: 2, category: "South Indian", emoji: "🥥" },
  "tomato rice":     { calorie: 210, protein: 3,  carbs: 38, fat: 5,  fiber: 2, category: "South Indian", emoji: "🍅" },
  "tamarind rice":   { calorie: 225, protein: 3,  carbs: 40, fat: 6,  fiber: 2, category: "South Indian", emoji: "🍚" },
  "rava idli":       { calorie: 90,  protein: 3,  carbs: 15, fat: 3,  fiber: 1, category: "South Indian", emoji: "🫓" },
  "set dosa":        { calorie: 140, protein: 3,  carbs: 24, fat: 4,  fiber: 1, category: "South Indian", emoji: "🥞" },
  // ── NORTH INDIAN ──────────────────────────────────────────────
  "aloo paratha":    { calorie: 300, protein: 5,  carbs: 48, fat: 10, fiber: 3, category: "North Indian", emoji: "🫓" },
  "paneer paratha":  { calorie: 330, protein: 8,  carbs: 44, fat: 13, fiber: 2, category: "North Indian", emoji: "🫓" },
  "chole bhature":   { calorie: 450, protein: 10, carbs: 60, fat: 18, fiber: 6, category: "North Indian", emoji: "🥘" },
  "rajma chawal":    { calorie: 350, protein: 10, carbs: 58, fat: 7,  fiber: 7, category: "North Indian", emoji: "🍚" },
  "dal makhani":     { calorie: 240, protein: 9,  carbs: 30, fat: 10, fiber: 5, category: "North Indian", emoji: "🍲" },
  kadhi:             { calorie: 180, protein: 6,  carbs: 22, fat: 7,  fiber: 2, category: "North Indian", emoji: "🍲" },
  "butter naan":     { calorie: 210, protein: 4,  carbs: 34, fat: 8,  fiber: 1, category: "North Indian", emoji: "🫓" },
  roti:              { calorie: 90,  protein: 3,  carbs: 18, fat: 1,  fiber: 2, category: "North Indian", emoji: "🫓" },
  "plain rice":      { calorie: 130, protein: 2,  carbs: 28, fat: 0,  fiber: 0, category: "North Indian", emoji: "🍚" },
  "kadhi pakora":    { calorie: 250, protein: 6,  carbs: 30, fat: 11, fiber: 2, category: "North Indian", emoji: "🍲" },
  "aloo tikki":      { calorie: 180, protein: 3,  carbs: 30, fat: 6,  fiber: 2, category: "North Indian", emoji: "🥔" },
  "malai kofta":     { calorie: 380, protein: 7,  carbs: 30, fat: 24, fiber: 3, category: "North Indian", emoji: "🥘" },
  "dal tadka":       { calorie: 200, protein: 8,  carbs: 28, fat: 7,  fiber: 5, category: "North Indian", emoji: "🍲" },
  "methi roti":      { calorie: 100, protein: 3,  carbs: 18, fat: 2,  fiber: 3, category: "North Indian", emoji: "🫓" },
  "aloo sabzi":      { calorie: 150, protein: 2,  carbs: 26, fat: 5,  fiber: 2, category: "North Indian", emoji: "🥔" },
  bhindi:            { calorie: 110, protein: 2,  carbs: 14, fat: 5,  fiber: 4, category: "North Indian", emoji: "🌿" },
  "palak paneer":    { calorie: 250, protein: 10, carbs: 14, fat: 16, fiber: 4, category: "North Indian", emoji: "🥬" },
  karela:            { calorie: 60,  protein: 1,  carbs: 10, fat: 2,  fiber: 3, category: "North Indian", emoji: "🥒" },
  "mix veg":         { calorie: 180, protein: 4,  carbs: 22, fat: 8,  fiber: 5, category: "North Indian", emoji: "🥘" },
  "matar paneer":    { calorie: 270, protein: 8,  carbs: 18, fat: 18, fiber: 4, category: "North Indian", emoji: "🫛" },
  "baingan bharta":  { calorie: 140, protein: 3,  carbs: 18, fat: 7,  fiber: 4, category: "North Indian", emoji: "🍆" },
  "shahi paneer":    { calorie: 320, protein: 11, carbs: 14, fat: 24, fiber: 1, category: "North Indian", emoji: "🧀" },
  "paneer tikka":    { calorie: 290, protein: 16, carbs: 10, fat: 20, fiber: 2, category: "North Indian", emoji: "🍢" },
  "chana masala":    { calorie: 270, protein: 11, carbs: 36, fat: 9,  fiber: 8, category: "North Indian", emoji: "🍲" },
  "moong dal":       { calorie: 160, protein: 9,  carbs: 22, fat: 3,  fiber: 5, category: "North Indian", emoji: "🟡" },
  "arhar dal":       { calorie: 180, protein: 10, carbs: 26, fat: 3,  fiber: 6, category: "North Indian", emoji: "🟡" },
  "masoor dal":      { calorie: 170, protein: 9,  carbs: 24, fat: 3,  fiber: 5, category: "North Indian", emoji: "🟠" },
  "stuffed capsicum":{ calorie: 160, protein: 4,  carbs: 22, fat: 6,  fiber: 3, category: "North Indian", emoji: "🫑" },
  "jeera rice":      { calorie: 170, protein: 3,  carbs: 32, fat: 4,  fiber: 0, category: "North Indian", emoji: "🍚" },
  kulcha:            { calorie: 240, protein: 5,  carbs: 38, fat: 8,  fiber: 1, category: "North Indian", emoji: "🫓" },
  "laccha paratha":  { calorie: 260, protein: 5,  carbs: 36, fat: 11, fiber: 2, category: "North Indian", emoji: "🫓" },
  // ── NON-VEG ──────────────────────────────────────────────────
  "boiled egg":      { calorie: 78,  protein: 6,  carbs: 0,  fat: 5,  fiber: 0, category: "Eggs & Non-Veg", emoji: "🥚" },
  omelette:          { calorie: 120, protein: 7,  carbs: 1,  fat: 9,  fiber: 0, category: "Eggs & Non-Veg", emoji: "🍳" },
  "chicken curry":   { calorie: 290, protein: 25, carbs: 12, fat: 16, fiber: 2, category: "Eggs & Non-Veg", emoji: "🍗" },
  "butter chicken":  { calorie: 430, protein: 23, carbs: 16, fat: 30, fiber: 1, category: "Eggs & Non-Veg", emoji: "🍗" },
  "mutton curry":    { calorie: 380, protein: 22, carbs: 10, fat: 26, fiber: 1, category: "Eggs & Non-Veg", emoji: "🥩" },
  "fish curry":      { calorie: 220, protein: 20, carbs: 8,  fat: 12, fiber: 1, category: "Eggs & Non-Veg", emoji: "🐟" },
  "grilled chicken": { calorie: 200, protein: 30, carbs: 0,  fat: 8,  fiber: 0, category: "Eggs & Non-Veg", emoji: "🍗" },
  "tandoori chicken":{ calorie: 260, protein: 32, carbs: 4,  fat: 11, fiber: 1, category: "Eggs & Non-Veg", emoji: "🍗" },
  "egg curry":       { calorie: 210, protein: 14, carbs: 10, fat: 13, fiber: 1, category: "Eggs & Non-Veg", emoji: "🥚" },
  "fish fry":        { calorie: 280, protein: 25, carbs: 12, fat: 15, fiber: 0, category: "Eggs & Non-Veg", emoji: "🐟" },
  keema:             { calorie: 330, protein: 22, carbs: 8,  fat: 22, fiber: 2, category: "Eggs & Non-Veg", emoji: "🥩" },
  "chicken biryani": { calorie: 400, protein: 18, carbs: 52, fat: 14, fiber: 2, category: "Eggs & Non-Veg", emoji: "🍛" },
  "mutton biryani":  { calorie: 450, protein: 20, carbs: 52, fat: 18, fiber: 2, category: "Eggs & Non-Veg", emoji: "🍛" },
  "prawn curry":     { calorie: 240, protein: 22, carbs: 10, fat: 13, fiber: 1, category: "Eggs & Non-Veg", emoji: "🦐" },
  "chicken 65":      { calorie: 310, protein: 28, carbs: 14, fat: 16, fiber: 1, category: "Eggs & Non-Veg", emoji: "🍗" },
  "scrambled eggs":  { calorie: 140, protein: 9,  carbs: 1,  fat: 10, fiber: 0, category: "Eggs & Non-Veg", emoji: "🍳" },
  "egg bhurji":      { calorie: 160, protein: 10, carbs: 4,  fat: 11, fiber: 1, category: "Eggs & Non-Veg", emoji: "🍳" },
  // ── BREAKFAST ─────────────────────────────────────────────────
  poha:              { calorie: 200, protein: 4,  carbs: 38, fat: 4,  fiber: 2, category: "Breakfast", emoji: "🍚" },
  daliya:            { calorie: 120, protein: 5,  carbs: 22, fat: 2,  fiber: 3, category: "Breakfast", emoji: "🌾" },
  oats:              { calorie: 110, protein: 4,  carbs: 20, fat: 2,  fiber: 3, category: "Breakfast", emoji: "🌾" },
  cornflakes:        { calorie: 120, protein: 2,  carbs: 26, fat: 0,  fiber: 1, category: "Breakfast", emoji: "🌽" },
  "bread butter":    { calorie: 160, protein: 3,  carbs: 24, fat: 7,  fiber: 1, category: "Breakfast", emoji: "🍞" },
  "bread jam":       { calorie: 180, protein: 2,  carbs: 36, fat: 2,  fiber: 1, category: "Breakfast", emoji: "🍞" },
  "moong dal chilla":{ calorie: 120, protein: 6,  carbs: 18, fat: 3,  fiber: 3, category: "Breakfast", emoji: "🥞" },
  "besan chilla":    { calorie: 140, protein: 6,  carbs: 20, fat: 4,  fiber: 3, category: "Breakfast", emoji: "🥞" },
  "veg sandwich":    { calorie: 250, protein: 5,  carbs: 40, fat: 7,  fiber: 3, category: "Breakfast", emoji: "🥪" },
  cheela:            { calorie: 160, protein: 6,  carbs: 22, fat: 5,  fiber: 2, category: "Breakfast", emoji: "🥞" },
  "egg sandwich":    { calorie: 220, protein: 9,  carbs: 30, fat: 8,  fiber: 2, category: "Breakfast", emoji: "🥪" },
  maggi:             { calorie: 350, protein: 7,  carbs: 52, fat: 12, fiber: 1, category: "Breakfast", emoji: "🍜" },
  muesli:            { calorie: 180, protein: 5,  carbs: 32, fat: 5,  fiber: 4, category: "Breakfast", emoji: "🌾" },
  "bread omelette":  { calorie: 290, protein: 12, carbs: 28, fat: 14, fiber: 2, category: "Breakfast", emoji: "🍳" },
  "masala oats":     { calorie: 140, protein: 5,  carbs: 22, fat: 4,  fiber: 4, category: "Breakfast", emoji: "🌾" },
  // ── SNACKS & STREET FOOD ──────────────────────────────────────
  samosa:            { calorie: 262, protein: 4,  carbs: 32, fat: 13, fiber: 2, category: "Snacks", emoji: "🥟" },
  pakora:            { calorie: 180, protein: 2,  carbs: 22, fat: 9,  fiber: 1, category: "Snacks", emoji: "🍤" },
  "bhel puri":       { calorie: 120, protein: 2,  carbs: 22, fat: 3,  fiber: 2, category: "Snacks", emoji: "🍿" },
  "sev puri":        { calorie: 200, protein: 3,  carbs: 30, fat: 8,  fiber: 2, category: "Snacks", emoji: "🍿" },
  "pav bhaji":       { calorie: 400, protein: 7,  carbs: 60, fat: 14, fiber: 5, category: "Snacks", emoji: "🍞" },
  "vada pav":        { calorie: 295, protein: 4,  carbs: 44, fat: 12, fiber: 2, category: "Snacks", emoji: "🍔" },
  kachori:           { calorie: 300, protein: 4,  carbs: 38, fat: 14, fiber: 2, category: "Snacks", emoji: "🥟" },
  "dahi puri":       { calorie: 210, protein: 5,  carbs: 32, fat: 7,  fiber: 2, category: "Snacks", emoji: "🥣" },
  "pani puri":       { calorie: 200, protein: 3,  carbs: 34, fat: 6,  fiber: 2, category: "Snacks", emoji: "🫙" },
  "aloo chaat":      { calorie: 230, protein: 3,  carbs: 38, fat: 7,  fiber: 3, category: "Snacks", emoji: "🥔" },
  "corn chaat":      { calorie: 180, protein: 4,  carbs: 32, fat: 4,  fiber: 4, category: "Snacks", emoji: "🌽" },
  dhokla:            { calorie: 160, protein: 6,  carbs: 28, fat: 3,  fiber: 2, category: "Snacks", emoji: "🍰" },
  momos:             { calorie: 180, protein: 6,  carbs: 28, fat: 5,  fiber: 1, category: "Snacks", emoji: "🥟" },
  "spring roll":     { calorie: 220, protein: 4,  carbs: 30, fat: 10, fiber: 2, category: "Snacks", emoji: "🌯" },
  // ── BIRYANI & RICE ────────────────────────────────────────────
  "veg biryani":     { calorie: 340, protein: 8,  carbs: 58, fat: 10, fiber: 4, category: "Rice & Biryani", emoji: "🍛" },
  "paneer biryani":  { calorie: 390, protein: 14, carbs: 56, fat: 14, fiber: 3, category: "Rice & Biryani", emoji: "🍛" },
  "egg biryani":     { calorie: 360, protein: 14, carbs: 52, fat: 12, fiber: 2, category: "Rice & Biryani", emoji: "🍛" },
  pulao:             { calorie: 270, protein: 6,  carbs: 46, fat: 7,  fiber: 3, category: "Rice & Biryani", emoji: "🍚" },
  khichdi:           { calorie: 200, protein: 7,  carbs: 36, fat: 3,  fiber: 4, category: "Rice & Biryani", emoji: "🍚" },
  "coconut rice":    { calorie: 240, protein: 3,  carbs: 40, fat: 8,  fiber: 1, category: "Rice & Biryani", emoji: "🥥" },
  // ── BEVERAGES ─────────────────────────────────────────────────
  milk:              { calorie: 150, protein: 8,  carbs: 12, fat: 8,  fiber: 0, category: "Beverages", emoji: "🥛" },
  lassi:             { calorie: 160, protein: 4,  carbs: 22, fat: 6,  fiber: 0, category: "Beverages", emoji: "🥛" },
  buttermilk:        { calorie: 40,  protein: 2,  carbs: 5,  fat: 1,  fiber: 0, category: "Beverages", emoji: "🥛" },
  tea:               { calorie: 30,  protein: 0,  carbs: 6,  fat: 1,  fiber: 0, category: "Beverages", emoji: "☕" },
  coffee:            { calorie: 50,  protein: 1,  carbs: 8,  fat: 2,  fiber: 0, category: "Beverages", emoji: "☕" },
  "coconut water":   { calorie: 45,  protein: 0,  carbs: 11, fat: 0,  fiber: 0, category: "Beverages", emoji: "🥥" },
  "sugarcane juice": { calorie: 180, protein: 0,  carbs: 44, fat: 0,  fiber: 0, category: "Beverages", emoji: "🧃" },
  "masala chai":     { calorie: 100, protein: 1,  carbs: 16, fat: 4,  fiber: 0, category: "Beverages", emoji: "☕" },
  "green tea":       { calorie: 5,   protein: 0,  carbs: 1,  fat: 0,  fiber: 0, category: "Beverages", emoji: "🍵" },
  "protein shake":   { calorie: 250, protein: 20, carbs: 20, fat: 5,  fiber: 1, category: "Beverages", emoji: "🥤" },
  "cold coffee":     { calorie: 180, protein: 4,  carbs: 24, fat: 7,  fiber: 0, category: "Beverages", emoji: "☕" },
  "badam milk":      { calorie: 210, protein: 6,  carbs: 26, fat: 9,  fiber: 1, category: "Beverages", emoji: "🥛" },
  "mango lassi":     { calorie: 200, protein: 4,  carbs: 34, fat: 5,  fiber: 1, category: "Beverages", emoji: "🥭" },
  "nimbu pani":      { calorie: 40,  protein: 0,  carbs: 10, fat: 0,  fiber: 0, category: "Beverages", emoji: "🍋" },
  // ── FRUITS ────────────────────────────────────────────────────
  banana:            { calorie: 90,  protein: 1,  carbs: 22, fat: 0,  fiber: 2, category: "Fruits", emoji: "🍌" },
  apple:             { calorie: 52,  protein: 0,  carbs: 14, fat: 0,  fiber: 2, category: "Fruits", emoji: "🍎" },
  mango:             { calorie: 99,  protein: 1,  carbs: 25, fat: 0,  fiber: 3, category: "Fruits", emoji: "🥭" },
  orange:            { calorie: 47,  protein: 1,  carbs: 12, fat: 0,  fiber: 2, category: "Fruits", emoji: "🍊" },
  papaya:            { calorie: 43,  protein: 1,  carbs: 11, fat: 0,  fiber: 2, category: "Fruits", emoji: "🍈" },
  grapes:            { calorie: 67,  protein: 1,  carbs: 17, fat: 0,  fiber: 1, category: "Fruits", emoji: "🍇" },
  guava:             { calorie: 68,  protein: 2,  carbs: 14, fat: 1,  fiber: 5, category: "Fruits", emoji: "🍐" },
  pear:              { calorie: 57,  protein: 0,  carbs: 15, fat: 0,  fiber: 3, category: "Fruits", emoji: "🍐" },
  watermelon:        { calorie: 30,  protein: 1,  carbs: 8,  fat: 0,  fiber: 0, category: "Fruits", emoji: "🍉" },
  lychee:            { calorie: 66,  protein: 1,  carbs: 17, fat: 0,  fiber: 1, category: "Fruits", emoji: "🍒" },
  pineapple:         { calorie: 50,  protein: 0,  carbs: 13, fat: 0,  fiber: 1, category: "Fruits", emoji: "🍍" },
  kiwi:              { calorie: 41,  protein: 1,  carbs: 10, fat: 0,  fiber: 2, category: "Fruits", emoji: "🥝" },
  pomegranate:       { calorie: 83,  protein: 2,  carbs: 19, fat: 1,  fiber: 4, category: "Fruits", emoji: "🍎" },
  strawberry:        { calorie: 32,  protein: 1,  carbs: 8,  fat: 0,  fiber: 2, category: "Fruits", emoji: "🍓" },
  // ── NUTS & DRY FRUITS ─────────────────────────────────────────
  almonds:           { calorie: 160, protein: 6,  carbs: 6,  fat: 14, fiber: 3, category: "Nuts & Dry Fruits", emoji: "🌰" },
  walnuts:           { calorie: 180, protein: 5,  carbs: 4,  fat: 18, fiber: 2, category: "Nuts & Dry Fruits", emoji: "🌰" },
  cashews:           { calorie: 155, protein: 5,  carbs: 9,  fat: 12, fiber: 1, category: "Nuts & Dry Fruits", emoji: "🌰" },
  raisins:           { calorie: 120, protein: 1,  carbs: 32, fat: 0,  fiber: 1, category: "Nuts & Dry Fruits", emoji: "🍇" },
  peanuts:           { calorie: 170, protein: 7,  carbs: 6,  fat: 14, fiber: 2, category: "Nuts & Dry Fruits", emoji: "🥜" },
  pistachios:        { calorie: 160, protein: 6,  carbs: 8,  fat: 13, fiber: 3, category: "Nuts & Dry Fruits", emoji: "🌱" },
  figs:              { calorie: 74,  protein: 1,  carbs: 19, fat: 0,  fiber: 3, category: "Nuts & Dry Fruits", emoji: "🍈" },
  dates:             { calorie: 90,  protein: 1,  carbs: 24, fat: 0,  fiber: 2, category: "Nuts & Dry Fruits", emoji: "🌴" },
  // ── SWEETS & DESSERTS ─────────────────────────────────────────
  "gulab jamun":     { calorie: 160, protein: 2,  carbs: 28, fat: 5,  fiber: 0, category: "Sweets", emoji: "🟤" },
  rasgulla:          { calorie: 125, protein: 3,  carbs: 24, fat: 2,  fiber: 0, category: "Sweets", emoji: "⚪" },
  kheer:             { calorie: 215, protein: 5,  carbs: 34, fat: 7,  fiber: 0, category: "Sweets", emoji: "🍮" },
  halwa:             { calorie: 250, protein: 3,  carbs: 40, fat: 9,  fiber: 1, category: "Sweets", emoji: "🍮" },
  barfi:             { calorie: 150, protein: 4,  carbs: 22, fat: 6,  fiber: 0, category: "Sweets", emoji: "🟪" },
  jalebi:            { calorie: 180, protein: 2,  carbs: 38, fat: 4,  fiber: 0, category: "Sweets", emoji: "🌀" },
  chikki:            { calorie: 200, protein: 4,  carbs: 28, fat: 9,  fiber: 1, category: "Sweets", emoji: "🟫" },
  peda:              { calorie: 160, protein: 3,  carbs: 26, fat: 5,  fiber: 0, category: "Sweets", emoji: "🟡" },
  "soan papdi":      { calorie: 150, protein: 2,  carbs: 26, fat: 5,  fiber: 0, category: "Sweets", emoji: "🟨" },
  "besan ladoo":     { calorie: 180, protein: 3,  carbs: 26, fat: 8,  fiber: 1, category: "Sweets", emoji: "🟠" },
  "moong dal halwa": { calorie: 280, protein: 4,  carbs: 38, fat: 12, fiber: 2, category: "Sweets", emoji: "🟡" },
  rasmalai:          { calorie: 250, protein: 5,  carbs: 32, fat: 11, fiber: 0, category: "Sweets", emoji: "🍮" },
  shrikhand:         { calorie: 200, protein: 6,  carbs: 28, fat: 8,  fiber: 0, category: "Sweets", emoji: "🍦" },
  kulfi:             { calorie: 180, protein: 4,  carbs: 24, fat: 8,  fiber: 0, category: "Sweets", emoji: "🍦" },
  rabri:             { calorie: 230, protein: 6,  carbs: 30, fat: 10, fiber: 0, category: "Sweets", emoji: "🍮" },
  malpua:            { calorie: 220, protein: 4,  carbs: 34, fat: 8,  fiber: 1, category: "Sweets", emoji: "🥞" },
};

export default foodDatabase;
