const foodDatabase = {
  // ── SOUTH INDIAN ──────────────────────────────────────────────
  "idli": { cal: 60, protein: 2.1, carbs: 12, fat: 0.4, fiber: 0.5, category: "South Indian", emoji: "🍚", tags: ["breakfast", "light", "healthy"] },
  "dosa": { cal: 168, protein: 3.5, carbs: 30, fat: 3.7, fiber: 1.2, category: "South Indian", emoji: "🥞", tags: ["breakfast"] },
  "masala dosa": { cal: 250, protein: 5, carbs: 38, fat: 8, fiber: 2, category: "South Indian", emoji: "🥞", tags: ["breakfast", "popular"] },
  "upma": { cal: 150, protein: 3, carbs: 22, fat: 5, fiber: 1.5, category: "South Indian", emoji: "🍲", tags: ["breakfast"] },
  "vada": { cal: 97, protein: 3, carbs: 14, fat: 4, fiber: 1, category: "South Indian", emoji: "🍩", tags: ["snack", "breakfast"] },
  "sambar": { cal: 80, protein: 4, carbs: 10, fat: 2, fiber: 3, category: "South Indian", emoji: "🥣", tags: ["side", "healthy"] },
  "rasam": { cal: 45, protein: 1.5, carbs: 8, fat: 1, fiber: 1, category: "South Indian", emoji: "🥣", tags: ["light", "healthy"] },
  "uttapam": { cal: 200, protein: 5, carbs: 32, fat: 5, fiber: 2, category: "South Indian", emoji: "🥞", tags: ["breakfast"] },
  "pongal": { cal: 190, protein: 5, carbs: 30, fat: 5, fiber: 2, category: "South Indian", emoji: "🍚", tags: ["breakfast"] },
  "lemon rice": { cal: 220, protein: 4, carbs: 42, fat: 5, fiber: 1, category: "South Indian", emoji: "🍋", tags: ["lunch"] },
  "curd rice": { cal: 180, protein: 6, carbs: 30, fat: 4, fiber: 0.5, category: "South Indian", emoji: "🍚", tags: ["lunch", "light"] },
  "avial": { cal: 160, protein: 3, carbs: 18, fat: 8, fiber: 4, category: "South Indian", emoji: "🥘", tags: ["lunch", "healthy"] },
  "kozhambu": { cal: 120, protein: 2, carbs: 12, fat: 6, fiber: 2, category: "South Indian", emoji: "🍲", tags: ["side"] },
  "idiyappam": { cal: 165, protein: 3, carbs: 34, fat: 1, fiber: 1, category: "South Indian", emoji: "🍜", tags: ["breakfast"] },
  "appam": { cal: 120, protein: 2, carbs: 24, fat: 1.5, fiber: 0.5, category: "South Indian", emoji: "🥞", tags: ["breakfast"] },
  "puttu": { cal: 200, protein: 4, carbs: 40, fat: 2, fiber: 2, category: "South Indian", emoji: "🍚", tags: ["breakfast"] },
  "pesarattu": { cal: 140, protein: 7, carbs: 22, fat: 3, fiber: 3, category: "South Indian", emoji: "🥞", tags: ["breakfast", "healthy"] },
  "bisi bele bath": { cal: 280, protein: 8, carbs: 45, fat: 7, fiber: 4, category: "South Indian", emoji: "🍲", tags: ["lunch"] },
  "medu vada": { cal: 110, protein: 4, carbs: 15, fat: 5, fiber: 1.5, category: "South Indian", emoji: "🍩", tags: ["snack"] },
  "coconut chutney": { cal: 80, protein: 1, carbs: 5, fat: 7, fiber: 2, category: "South Indian", emoji: "🥥", tags: ["side", "condiment"] },

  // ── NORTH INDIAN ───────────────────────────────────────────────
  "aloo paratha": { cal: 300, protein: 6, carbs: 45, fat: 10, fiber: 3, category: "North Indian", emoji: "🫓", tags: ["breakfast", "popular"] },
  "paneer paratha": { cal: 350, protein: 12, carbs: 40, fat: 14, fiber: 2, category: "North Indian", emoji: "🫓", tags: ["breakfast"] },
  "chole bhature": { cal: 490, protein: 14, carbs: 65, fat: 18, fiber: 8, category: "North Indian", emoji: "🍛", tags: ["lunch", "heavy"] },
  "rajma chawal": { cal: 350, protein: 12, carbs: 58, fat: 6, fiber: 9, category: "North Indian", emoji: "🍛", tags: ["lunch", "protein"] },
  "dal makhani": { cal: 240, protein: 10, carbs: 28, fat: 10, fiber: 6, category: "North Indian", emoji: "🥘", tags: ["dinner", "protein"] },
  "kadhi": { cal: 160, protein: 6, carbs: 18, fat: 7, fiber: 2, category: "North Indian", emoji: "🥣", tags: ["lunch"] },
  "butter naan": { cal: 310, protein: 8, carbs: 52, fat: 8, fiber: 2, category: "North Indian", emoji: "🫓", tags: ["dinner"] },
  "roti": { cal: 90, protein: 3, carbs: 18, fat: 1.5, fiber: 2, category: "North Indian", emoji: "🫓", tags: ["staple", "healthy"] },
  "plain rice": { cal: 130, protein: 2.5, carbs: 28, fat: 0.3, fiber: 0.4, category: "North Indian", emoji: "🍚", tags: ["staple"] },
  "kadhi pakora": { cal: 250, protein: 8, carbs: 28, fat: 11, fiber: 3, category: "North Indian", emoji: "🥘", tags: ["lunch"] },
  "aloo tikki": { cal: 180, protein: 3, carbs: 28, fat: 7, fiber: 2, category: "North Indian", emoji: "🥔", tags: ["snack", "street food"] },
  "malai kofta": { cal: 380, protein: 9, carbs: 30, fat: 24, fiber: 3, category: "North Indian", emoji: "🥘", tags: ["dinner", "rich"] },
  "dal tadka": { cal: 190, protein: 10, carbs: 25, fat: 6, fiber: 6, category: "North Indian", emoji: "🥣", tags: ["lunch", "protein", "healthy"] },
  "methi roti": { cal: 110, protein: 4, carbs: 19, fat: 2.5, fiber: 3, category: "North Indian", emoji: "🫓", tags: ["healthy", "staple"] },
  "stuffed capsicum": { cal: 160, protein: 5, carbs: 18, fat: 7, fiber: 3, category: "North Indian", emoji: "🫑", tags: ["dinner", "healthy"] },
  "chana masala": { cal: 270, protein: 12, carbs: 38, fat: 8, fiber: 10, category: "North Indian", emoji: "🍛", tags: ["lunch", "protein", "healthy"] },
  "puri bhaji": { cal: 380, protein: 7, carbs: 55, fat: 14, fiber: 4, category: "North Indian", emoji: "🍛", tags: ["breakfast", "heavy"] },
  "paneer tikka": { cal: 290, protein: 18, carbs: 10, fat: 20, fiber: 2, category: "North Indian", emoji: "🧀", tags: ["snack", "protein", "popular"] },
  "shahi paneer": { cal: 380, protein: 14, carbs: 18, fat: 28, fiber: 2, category: "North Indian", emoji: "🥘", tags: ["dinner", "rich"] },
  "jeera rice": { cal: 160, protein: 3, carbs: 32, fat: 3, fiber: 0.5, category: "North Indian", emoji: "🍚", tags: ["staple"] },
  "dal baati": { cal: 450, protein: 14, carbs: 60, fat: 16, fiber: 8, category: "North Indian", emoji: "🍞", tags: ["lunch", "rajasthani"] },
  "moong dal": { cal: 150, protein: 10, carbs: 20, fat: 2, fiber: 7, category: "North Indian", emoji: "🥣", tags: ["healthy", "protein", "light"] },
  "arhar dal": { cal: 160, protein: 11, carbs: 22, fat: 2.5, fiber: 6, category: "North Indian", emoji: "🥣", tags: ["protein", "healthy"] },
  "masoor dal": { cal: 140, protein: 10, carbs: 20, fat: 1.5, fiber: 5, category: "North Indian", emoji: "🥣", tags: ["healthy", "protein"] },
  "aloo gobi": { cal: 150, protein: 4, carbs: 22, fat: 5, fiber: 4, category: "North Indian", emoji: "🥦", tags: ["lunch", "healthy"] },
  "matar paneer": { cal: 270, protein: 12, carbs: 22, fat: 16, fiber: 4, category: "North Indian", emoji: "🥘", tags: ["dinner"] },
  "palak paneer": { cal: 250, protein: 13, carbs: 14, fat: 17, fiber: 4, category: "North Indian", emoji: "🥬", tags: ["dinner", "iron-rich"] },
  "baingan bharta": { cal: 130, protein: 3, carbs: 16, fat: 6, fiber: 5, category: "North Indian", emoji: "🍆", tags: ["dinner", "healthy"] },
  "aloo sabzi": { cal: 145, protein: 3, carbs: 24, fat: 5, fiber: 3, category: "North Indian", emoji: "🥔", tags: ["lunch"] },
  "bhindi masala": { cal: 110, protein: 2.5, carbs: 12, fat: 6, fiber: 4, category: "North Indian", emoji: "🫑", tags: ["healthy", "lunch"] },
  "karela sabzi": { cal: 70, protein: 2, carbs: 8, fat: 3, fiber: 3, category: "North Indian", emoji: "🥒", tags: ["healthy", "diabetic-friendly"] },
  "lauki sabzi": { cal: 80, protein: 2, carbs: 10, fat: 3, fiber: 2, category: "North Indian", emoji: "🥒", tags: ["light", "healthy"] },
  "mix veg": { cal: 170, protein: 4, carbs: 20, fat: 8, fiber: 4, category: "North Indian", emoji: "🥘", tags: ["lunch", "healthy"] },
  "dum aloo": { cal: 220, protein: 4, carbs: 30, fat: 10, fiber: 3, category: "North Indian", emoji: "🥔", tags: ["dinner"] },

  // ── BIRYANI & RICE ─────────────────────────────────────────────
  "chicken biryani": { cal: 490, protein: 28, carbs: 58, fat: 14, fiber: 2, category: "Biryani & Rice", emoji: "🍛", tags: ["lunch", "dinner", "popular"] },
  "mutton biryani": { cal: 540, protein: 30, carbs: 58, fat: 18, fiber: 2, category: "Biryani & Rice", emoji: "🍛", tags: ["lunch", "dinner", "heavy"] },
  "veg biryani": { cal: 350, protein: 8, carbs: 62, fat: 8, fiber: 4, category: "Biryani & Rice", emoji: "🍛", tags: ["lunch"] },
  "paneer biryani": { cal: 420, protein: 16, carbs: 60, fat: 12, fiber: 3, category: "Biryani & Rice", emoji: "🍛", tags: ["lunch"] },
  "egg biryani": { cal: 410, protein: 20, carbs: 58, fat: 12, fiber: 2, category: "Biryani & Rice", emoji: "🍛", tags: ["lunch"] },
  "pulao": { cal: 220, protein: 5, carbs: 42, fat: 4, fiber: 2, category: "Biryani & Rice", emoji: "🍚", tags: ["lunch"] },
  "khichdi": { cal: 200, protein: 8, carbs: 35, fat: 4, fiber: 4, category: "Biryani & Rice", emoji: "🍲", tags: ["light", "healthy", "comfort"] },
  "fried rice": { cal: 290, protein: 7, carbs: 48, fat: 8, fiber: 2, category: "Biryani & Rice", emoji: "🍳", tags: ["lunch"] },

  // ── NON VEGETARIAN ─────────────────────────────────────────────
  "boiled egg": { cal: 78, protein: 6.3, carbs: 0.6, fat: 5.3, fiber: 0, category: "Eggs & Meat", emoji: "🥚", tags: ["breakfast", "protein", "healthy"] },
  "omelette": { cal: 154, protein: 10, carbs: 1, fat: 12, fiber: 0, category: "Eggs & Meat", emoji: "🍳", tags: ["breakfast", "protein"] },
  "scrambled eggs": { cal: 148, protein: 10, carbs: 2, fat: 11, fiber: 0, category: "Eggs & Meat", emoji: "🍳", tags: ["breakfast", "protein"] },
  "egg curry": { cal: 210, protein: 14, carbs: 10, fat: 14, fiber: 2, category: "Eggs & Meat", emoji: "🥘", tags: ["lunch", "protein"] },
  "chicken curry": { cal: 290, protein: 26, carbs: 10, fat: 16, fiber: 2, category: "Eggs & Meat", emoji: "🍗", tags: ["dinner", "protein"] },
  "butter chicken": { cal: 430, protein: 30, carbs: 18, fat: 26, fiber: 2, category: "Eggs & Meat", emoji: "🍗", tags: ["dinner", "popular", "rich"] },
  "mutton curry": { cal: 390, protein: 28, carbs: 8, fat: 28, fiber: 1, category: "Eggs & Meat", emoji: "🥘", tags: ["dinner", "protein", "heavy"] },
  "fish curry": { cal: 220, protein: 24, carbs: 8, fat: 10, fiber: 1, category: "Eggs & Meat", emoji: "🐟", tags: ["dinner", "protein", "omega-3"] },
  "grilled chicken": { cal: 200, protein: 35, carbs: 0, fat: 6, fiber: 0, category: "Eggs & Meat", emoji: "🍗", tags: ["protein", "healthy", "gym"] },
  "tandoori chicken": { cal: 260, protein: 36, carbs: 6, fat: 10, fiber: 1, category: "Eggs & Meat", emoji: "🍗", tags: ["protein", "popular"] },
  "fish fry": { cal: 280, protein: 26, carbs: 12, fat: 14, fiber: 0, category: "Eggs & Meat", emoji: "🐟", tags: ["dinner"] },
  "keema": { cal: 330, protein: 26, carbs: 8, fat: 22, fiber: 2, category: "Eggs & Meat", emoji: "🥘", tags: ["dinner", "protein"] },
  "chicken tikka": { cal: 240, protein: 34, carbs: 5, fat: 9, fiber: 1, category: "Eggs & Meat", emoji: "🍢", tags: ["protein", "gym", "popular"] },
  "prawn curry": { cal: 250, protein: 22, carbs: 10, fat: 14, fiber: 1, category: "Eggs & Meat", emoji: "🦐", tags: ["dinner", "protein"] },
  "chicken 65": { cal: 310, protein: 28, carbs: 15, fat: 16, fiber: 1, category: "Eggs & Meat", emoji: "🍗", tags: ["snack", "popular"] },

  // ── STREET FOOD ────────────────────────────────────────────────
  "samosa": { cal: 262, protein: 4, carbs: 30, fat: 14, fiber: 2, category: "Street Food", emoji: "🥟", tags: ["snack", "popular", "street food"] },
  "pakora": { cal: 200, protein: 5, carbs: 22, fat: 10, fiber: 2, category: "Street Food", emoji: "🧆", tags: ["snack", "monsoon"] },
  "bhel puri": { cal: 180, protein: 5, carbs: 30, fat: 5, fiber: 3, category: "Street Food", emoji: "🥗", tags: ["snack", "street food"] },
  "sev puri": { cal: 210, protein: 5, carbs: 28, fat: 9, fiber: 2, category: "Street Food", emoji: "🥗", tags: ["snack", "street food"] },
  "pav bhaji": { cal: 450, protein: 10, carbs: 65, fat: 16, fiber: 6, category: "Street Food", emoji: "🍞", tags: ["dinner", "street food", "popular"] },
  "vada pav": { cal: 300, protein: 7, carbs: 42, fat: 12, fiber: 3, category: "Street Food", emoji: "🍔", tags: ["snack", "street food", "popular"] },
  "kachori": { cal: 320, protein: 6, carbs: 38, fat: 16, fiber: 3, category: "Street Food", emoji: "🥟", tags: ["snack", "heavy"] },
  "pani puri": { cal: 200, protein: 4, carbs: 32, fat: 6, fiber: 2, category: "Street Food", emoji: "🫧", tags: ["snack", "street food", "popular"] },
  "dahi puri": { cal: 240, protein: 7, carbs: 34, fat: 8, fiber: 2, category: "Street Food", emoji: "🫧", tags: ["snack", "street food"] },
  "aloo chaat": { cal: 220, protein: 5, carbs: 35, fat: 7, fiber: 4, category: "Street Food", emoji: "🥔", tags: ["snack", "street food"] },
  "dabeli": { cal: 280, protein: 7, carbs: 40, fat: 10, fiber: 3, category: "Street Food", emoji: "🍔", tags: ["snack", "street food"] },
  "ragda pattice": { cal: 350, protein: 10, carbs: 52, fat: 10, fiber: 6, category: "Street Food", emoji: "🥘", tags: ["snack", "street food"] },
  "misal pav": { cal: 380, protein: 14, carbs: 55, fat: 10, fiber: 8, category: "Street Food", emoji: "🍲", tags: ["breakfast", "street food", "maharashtrian"] },
  "puchka": { cal: 150, protein: 3, carbs: 26, fat: 4, fiber: 2, category: "Street Food", emoji: "🫧", tags: ["snack", "street food", "bengali"] },

  // ── BREAKFAST ─────────────────────────────────────────────────
  "poha": { cal: 200, protein: 4, carbs: 36, fat: 5, fiber: 2, category: "Breakfast", emoji: "🍽", tags: ["breakfast", "light"] },
  "bread butter": { cal: 200, protein: 5, carbs: 28, fat: 8, fiber: 1.5, category: "Breakfast", emoji: "🍞", tags: ["breakfast", "quick"] },
  "bread jam": { cal: 220, protein: 4, carbs: 42, fat: 3, fiber: 1.5, category: "Breakfast", emoji: "🍞", tags: ["breakfast", "quick"] },
  "cornflakes": { cal: 160, protein: 3, carbs: 36, fat: 0.5, fiber: 2, category: "Breakfast", emoji: "🥣", tags: ["breakfast", "quick"] },
  "oats": { cal: 150, protein: 5, carbs: 27, fat: 3, fiber: 4, category: "Breakfast", emoji: "🥣", tags: ["breakfast", "healthy", "fiber"] },
  "daliya": { cal: 130, protein: 5, carbs: 26, fat: 2, fiber: 5, category: "Breakfast", emoji: "🥣", tags: ["breakfast", "healthy"] },
  "maggi": { cal: 350, protein: 8, carbs: 50, fat: 12, fiber: 2, category: "Breakfast", emoji: "🍜", tags: ["quick", "comfort"] },
  "moong dal chilla": { cal: 130, protein: 8, carbs: 18, fat: 3, fiber: 4, category: "Breakfast", emoji: "🥞", tags: ["breakfast", "healthy", "protein"] },
  "besan chilla": { cal: 150, protein: 8, carbs: 20, fat: 4, fiber: 4, category: "Breakfast", emoji: "🥞", tags: ["breakfast", "healthy", "protein"] },
  "veg sandwich": { cal: 280, protein: 8, carbs: 42, fat: 8, fiber: 4, category: "Breakfast", emoji: "🥪", tags: ["breakfast", "quick"] },
  "egg sandwich": { cal: 320, protein: 16, carbs: 36, fat: 14, fiber: 2, category: "Breakfast", emoji: "🥪", tags: ["breakfast", "protein"] },
  "cheela": { cal: 160, protein: 7, carbs: 22, fat: 5, fiber: 3, category: "Breakfast", emoji: "🥞", tags: ["breakfast", "healthy"] },
  "thepla": { cal: 180, protein: 5, carbs: 28, fat: 6, fiber: 3, category: "Breakfast", emoji: "🫓", tags: ["breakfast", "gujarati"] },
  "dhokla": { cal: 160, protein: 6, carbs: 26, fat: 4, fiber: 2, category: "Breakfast", emoji: "🟡", tags: ["breakfast", "gujarati", "healthy"] },
  "sabudana khichdi": { cal: 300, protein: 4, carbs: 58, fat: 8, fiber: 1, category: "Breakfast", emoji: "🍲", tags: ["breakfast", "fasting"] },
  "muesli": { cal: 200, protein: 6, carbs: 40, fat: 4, fiber: 5, category: "Breakfast", emoji: "🥣", tags: ["breakfast", "healthy"] },
  "granola": { cal: 240, protein: 5, carbs: 42, fat: 8, fiber: 4, category: "Breakfast", emoji: "🥣", tags: ["breakfast"] },
  "upma with vegetables": { cal: 180, protein: 5, carbs: 28, fat: 6, fiber: 3, category: "Breakfast", emoji: "🍲", tags: ["breakfast", "healthy"] },

  // ── FRUITS ────────────────────────────────────────────────────
  "banana": { cal: 90, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, category: "Fruits", emoji: "🍌", tags: ["fruit", "energy", "gym"] },
  "apple": { cal: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, category: "Fruits", emoji: "🍎", tags: ["fruit", "healthy"] },
  "mango": { cal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, category: "Fruits", emoji: "🥭", tags: ["fruit", "summer"] },
  "orange": { cal: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, category: "Fruits", emoji: "🍊", tags: ["fruit", "vitamin-c"] },
  "papaya": { cal: 43, protein: 0.5, carbs: 11, fat: 0.3, fiber: 1.7, category: "Fruits", emoji: "🍈", tags: ["fruit", "digestive"] },
  "grapes": { cal: 67, protein: 0.6, carbs: 17, fat: 0.4, fiber: 0.9, category: "Fruits", emoji: "🍇", tags: ["fruit"] },
  "guava": { cal: 68, protein: 2.6, carbs: 14, fat: 1, fiber: 5.4, category: "Fruits", emoji: "🍐", tags: ["fruit", "vitamin-c", "fiber"] },
  "watermelon": { cal: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, category: "Fruits", emoji: "🍉", tags: ["fruit", "hydrating", "summer"] },
  "pomegranate": { cal: 83, protein: 1.7, carbs: 19, fat: 1.2, fiber: 4, category: "Fruits", emoji: "🔴", tags: ["fruit", "antioxidant"] },
  "pineapple": { cal: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, category: "Fruits", emoji: "🍍", tags: ["fruit", "tropical"] },
  "kiwi": { cal: 61, protein: 1.1, carbs: 15, fat: 0.5, fiber: 3, category: "Fruits", emoji: "🥝", tags: ["fruit", "vitamin-c"] },
  "strawberry": { cal: 32, protein: 0.7, carbs: 8, fat: 0.3, fiber: 2, category: "Fruits", emoji: "🍓", tags: ["fruit", "antioxidant"] },
  "pear": { cal: 57, protein: 0.4, carbs: 15, fat: 0.1, fiber: 3.1, category: "Fruits", emoji: "🍐", tags: ["fruit", "fiber"] },
  "lychee": { cal: 66, protein: 0.8, carbs: 17, fat: 0.4, fiber: 1.3, category: "Fruits", emoji: "🔴", tags: ["fruit", "summer"] },
  "chikoo": { cal: 83, protein: 0.4, carbs: 20, fat: 1.1, fiber: 5.3, category: "Fruits", emoji: "🟤", tags: ["fruit"] },

  // ── BEVERAGES ─────────────────────────────────────────────────
  "milk": { cal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, category: "Beverages", emoji: "🥛", tags: ["drink", "calcium", "healthy"] },
  "lassi": { cal: 150, protein: 5, carbs: 20, fat: 5, fiber: 0, category: "Beverages", emoji: "🥛", tags: ["drink", "probiotic"] },
  "buttermilk": { cal: 40, protein: 3, carbs: 5, fat: 1, fiber: 0, category: "Beverages", emoji: "🥛", tags: ["drink", "light", "digestive"] },
  "masala chai": { cal: 100, protein: 2, carbs: 14, fat: 4, fiber: 0, category: "Beverages", emoji: "☕", tags: ["drink", "popular"] },
  "green tea": { cal: 5, protein: 0, carbs: 1, fat: 0, fiber: 0, category: "Beverages", emoji: "🍵", tags: ["drink", "healthy", "antioxidant"] },
  "black coffee": { cal: 5, protein: 0.3, carbs: 0, fat: 0, fiber: 0, category: "Beverages", emoji: "☕", tags: ["drink", "energy"] },
  "coconut water": { cal: 45, protein: 1.7, carbs: 9, fat: 0.5, fiber: 3, category: "Beverages", emoji: "🥥", tags: ["drink", "hydrating", "healthy"] },
  "sugarcane juice": { cal: 180, protein: 0.5, carbs: 44, fat: 0.5, fiber: 0, category: "Beverages", emoji: "🥤", tags: ["drink", "energy"] },
  "protein shake": { cal: 250, protein: 25, carbs: 15, fat: 5, fiber: 2, category: "Beverages", emoji: "💪", tags: ["drink", "gym", "protein"] },
  "cold coffee": { cal: 200, protein: 5, carbs: 28, fat: 7, fiber: 0, category: "Beverages", emoji: "☕", tags: ["drink"] },
  "badam milk": { cal: 220, protein: 7, carbs: 28, fat: 9, fiber: 1, category: "Beverages", emoji: "🥛", tags: ["drink", "nutritious"] },
  "mango lassi": { cal: 190, protein: 5, carbs: 32, fat: 5, fiber: 1, category: "Beverages", emoji: "🥭", tags: ["drink", "summer"] },
  "turmeric milk": { cal: 120, protein: 4, carbs: 12, fat: 5, fiber: 0, category: "Beverages", emoji: "🥛", tags: ["drink", "healthy", "immunity"] },
  "nimbu pani": { cal: 30, protein: 0.2, carbs: 8, fat: 0, fiber: 0, category: "Beverages", emoji: "🍋", tags: ["drink", "hydrating"] },
  "jaljeera": { cal: 40, protein: 0.5, carbs: 10, fat: 0.2, fiber: 0.5, category: "Beverages", emoji: "🥤", tags: ["drink", "digestive"] },

  // ── NUTS & DRY FRUITS ──────────────────────────────────────────
  "almonds": { cal: 160, protein: 6, carbs: 6, fat: 14, fiber: 3.5, category: "Nuts & Dry Fruits", emoji: "🌰", tags: ["healthy", "protein", "gym"] },
  "walnuts": { cal: 185, protein: 4, carbs: 4, fat: 18, fiber: 2, category: "Nuts & Dry Fruits", emoji: "🌰", tags: ["healthy", "omega-3"] },
  "cashews": { cal: 157, protein: 5, carbs: 9, fat: 12, fiber: 1, category: "Nuts & Dry Fruits", emoji: "🌰", tags: ["healthy", "protein"] },
  "peanuts": { cal: 170, protein: 8, carbs: 5, fat: 14, fiber: 2.5, category: "Nuts & Dry Fruits", emoji: "🥜", tags: ["healthy", "protein", "cheap"] },
  "pistachios": { cal: 159, protein: 6, carbs: 8, fat: 13, fiber: 3, category: "Nuts & Dry Fruits", emoji: "🌰", tags: ["healthy", "protein"] },
  "raisins": { cal: 120, protein: 1, carbs: 30, fat: 0.2, fiber: 1.9, category: "Nuts & Dry Fruits", emoji: "🍇", tags: ["energy", "iron"] },
  "dates": { cal: 90, protein: 0.8, carbs: 24, fat: 0.1, fiber: 2.4, category: "Nuts & Dry Fruits", emoji: "🟤", tags: ["energy", "fiber"] },
  "figs": { cal: 74, protein: 1, carbs: 19, fat: 0.3, fiber: 2.9, category: "Nuts & Dry Fruits", emoji: "🟣", tags: ["fiber", "calcium"] },

  // ── SWEETS & DESSERTS ──────────────────────────────────────────
  "gulab jamun": { cal: 175, protein: 3, carbs: 30, fat: 6, fiber: 0.5, category: "Sweets", emoji: "🟤", tags: ["dessert", "sweet", "festival"] },
  "rasgulla": { cal: 110, protein: 4, carbs: 22, fat: 1.5, fiber: 0, category: "Sweets", emoji: "⚪", tags: ["dessert", "bengali"] },
  "kheer": { cal: 220, protein: 6, carbs: 36, fat: 6, fiber: 0.3, category: "Sweets", emoji: "🍮", tags: ["dessert", "festival"] },
  "halwa": { cal: 280, protein: 4, carbs: 42, fat: 10, fiber: 2, category: "Sweets", emoji: "🟡", tags: ["dessert", "festival"] },
  "barfi": { cal: 180, protein: 5, carbs: 28, fat: 6, fiber: 0.5, category: "Sweets", emoji: "🟡", tags: ["dessert", "festival"] },
  "jalebi": { cal: 200, protein: 2, carbs: 38, fat: 5, fiber: 0.3, category: "Sweets", emoji: "🍭", tags: ["dessert", "sweet"] },
  "ladoo": { cal: 200, protein: 4, carbs: 30, fat: 8, fiber: 1, category: "Sweets", emoji: "🟠", tags: ["dessert", "festival"] },
  "rasmalai": { cal: 260, protein: 8, carbs: 34, fat: 10, fiber: 0.3, category: "Sweets", emoji: "⚪", tags: ["dessert", "bengali"] },
  "shrikhand": { cal: 210, protein: 7, carbs: 32, fat: 7, fiber: 0, category: "Sweets", emoji: "🟡", tags: ["dessert", "gujarati"] },
  "ice cream": { cal: 200, protein: 3.5, carbs: 28, fat: 9, fiber: 0, category: "Sweets", emoji: "🍦", tags: ["dessert", "popular"] },
  "payasam": { cal: 240, protein: 6, carbs: 40, fat: 7, fiber: 1, category: "Sweets", emoji: "🍮", tags: ["dessert", "south indian"] },
  "gajar halwa": { cal: 260, protein: 5, carbs: 38, fat: 10, fiber: 3, category: "Sweets", emoji: "🥕", tags: ["dessert", "winter"] },
  "malpua": { cal: 280, protein: 5, carbs: 42, fat: 10, fiber: 1, category: "Sweets", emoji: "🥞", tags: ["dessert", "festival"] },

  // ── SALADS & HEALTHY ──────────────────────────────────────────
  "green salad": { cal: 50, protein: 2, carbs: 8, fat: 1, fiber: 3, category: "Salads", emoji: "🥗", tags: ["healthy", "light", "diet"] },
  "fruit salad": { cal: 100, protein: 1.5, carbs: 25, fat: 0.5, fiber: 3, category: "Salads", emoji: "🥗", tags: ["healthy", "light", "diet"] },
  "sprouts salad": { cal: 80, protein: 6, carbs: 12, fat: 1, fiber: 4, category: "Salads", emoji: "🌱", tags: ["healthy", "protein", "diet"] },
  "cucumber raita": { cal: 70, protein: 4, carbs: 8, fat: 2, fiber: 1, category: "Salads", emoji: "🥒", tags: ["healthy", "side", "cooling"] },
  "boondi raita": { cal: 120, protein: 5, carbs: 14, fat: 5, fiber: 1, category: "Salads", emoji: "🥣", tags: ["side"] },
  "kachumber salad": { cal: 60, protein: 2, carbs: 10, fat: 1, fiber: 3, category: "Salads", emoji: "🥗", tags: ["healthy", "light"] },
};

export default foodDatabase;
